server:
  port: 8080

spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://localhost:5434/customer-db
    username: admin
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true