version: '3'

services:
  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: customer-db
    volumes:
    - customer:/data/postgres
    ports:
    - "5434:5432"
    networks:
      - postgres
    restart: always

  fraud-db:
    image: postgres
    container_name: fraud-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fraud-db
    volumes:
      - fraud:/data/postgres
    ports:
    - "5435:5432"
    networks:
      - postgres
    restart: always

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: notification-db
    volumes:
      - notification:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - postgres
    restart: always

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge

volumes:
  customer:
  fraud:
  notification:
