server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5435/fraud-db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka